etcd: ["10.77.50.208:2381", "10.77.50.209:2381", "10.77.50.211:2381"]
sites: {
  main: {
    sitename: main,
    ip: 10.77.50.211,
    port: 5600,
  },
  segment1: {
    sitename: segment1,
    ip: 10.77.50.208,
    port: 5600,
  },
  segment2: {
    sitename: segment2,
    ip: 10.77.50.209,
    port: 5600,
  },
  segment3: {
    sitename: segment3,
    ip: 10.77.50.209,
    port: 5601,
  }
}
dbs: {
    main: {
      dbname: postgres,
      port: 5700,
      user: postgres,
      password: postgres,
      sslmode: disable
    },
    segment1: {
      dbname: postgres,
      port: 5700,
      user: postgres,
      password: postgres,
      sslmode: disable
    },
    segment2: {
      dbname: postgres,
      port: 5700,
      user: postgres,
      password: postgres,
      sslmode: disable
    },
    segment3: {
      dbname: postgres,
      port: 5701,
      user: postgres,
      password: postgres,
      sslmode: disable
    }
}